# Generated by Django 4.1 on 2022-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/deafult.png', upload_to='images/'),
        ),
    ]
