# Generated by Django 4.1 on 2022-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/deafult.jpg', upload_to='images/'),
        ),
    ]
