# Generated by Django 4.1 on 2022-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_card_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('İsim', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Mesaj', models.TextField()),
                ('Tarih', models.DateTimeField()),
            ],
        ),
    ]
