# Generated by Django 4.1 on 2022-12-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Tarih',
        ),
    ]
