# Generated by Django 4.1 on 2022-12-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_remove_contact_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='card',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
