# Generated by Django 4.1 on 2022-12-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_alter_slider_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
